---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: build-buildpack-builder
  type: git
  check_every: 2m
  source:
    uri: https://github.com/xiujuan95/build-buildpack-builder
    branch: master
    # private_key: ((git-private-key))
    disable_ci_skip: true

- name: paketo-image
  type: docker-image
  check_every: 2m
  source:
    repository: paketobuildpacks/builder
    tag: full

# - name: slack
#   type: slack-notification
#   tags: [buildpacks]
#   source:
#     url: ((slack-webhook))

jobs:
- name: check-paketo-update
  plan:
  - get: build-buildpack-builder
    trigger: true
  - get: paketo-image
    trigger: true
  - task: check
    privileged: true
    # tags: [buildpacks]
    # on_failure:
    #   put: slack
    #   params:
    #     text: |
    #       :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: latest } }
      inputs:
      - name: paketo-image
      - name: build-buildpack-builder
        path: build-buildpack-builder
      params:
        # SLACK_URL: ((slack-url))
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/check.sh" ))

- name: build-buildpack-builder
  plan:
  - get: build-buildpack-builder
    trigger: true
  - get: paketo-image
    passed: [check-paketo-update]
    trigger: true
  - task: build
    privileged: true
    # on_failure:
    #   put: slack
    #   params:
    #     text: |
    #       :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: latest } }
      inputs:
      - name: paketo-image
      - name: build-buildpack-builder
        path: build-buildpack-builder
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/build.sh" ))

- name: test-buildpack-builder
  plan:
  - get: build-buildpack-builder
    trigger: true
  - get: paketo-image
    passed: [build-buildpack-builder]
    trigger: true
  - task: test
    privileged: true
    # on_failure:
    #   put: slack
    #   params:
    #     text: |
    #       :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: latest } }
      inputs:
      - name: paketo-image
      - name: build-buildpack-builder
        path: build-buildpack-builder
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/test.sh" ))

- name: submit-pr
  plan:
  - get: build-buildpack-builder
    trigger: true
  - get: paketo-image
    passed: [test-buildpack-builder]
    trigger: true
  - task: pr
    privileged: true
    # on_failure:
    #   put: slack
    #   params:
    #     text: |
    #       :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: latest } }
      inputs:
      - name: paketo-image
      - name: build-buildpack-builder
        path: build-buildpack-builder
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/submit-pr.sh" ))
      