---
resources:
- name: paketo-image
  type: docker-image
  tags: [buildpacks]
  check_every: 2m
  source:
    repository: index.docker.io/paketobuildpacks/builder
    tag: full

jobs:
- name: check-paketo-update
  plan:
  - get: paketo-image
    tags: [buildpacks]
    trigger: true
  - task: check
    tags: [buildpacks]
    on_failure:
      put: slack
      params:
        text: |
          :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: ((bwb-image-version)) } }
      inputs:
      - name: paketo-image
      params:
        SLACK_URL: ((aio-bosh-sl-cpi-slack-url))
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/check.sh" ))

- name: build-buildpack-builder
  plan:
  - get: paketo-image
    tags: [buildpacks]
    passed: [check-paketo-update]
    trigger: true
  - task: build
    tags: [buildpacks]
    on_failure:
      put: slack
      params:
        text: |
          :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: ((bwb-image-version)) } }
      inputs:
      - name: paketo-image
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/build.sh" ))

- name: test-buildpack-builder
  plan:
  - get: paketo-image
    tags: [buildpacks]
    passed: [build-buildpack-builder]
    trigger: true
  - task: test
    tags: [buildpacks]
    on_failure:
      put: slack
      params:
        text: |
          :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: ((bwb-image-version)) } }
      inputs:
      - name: paketo-image
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/test.sh" ))

- name: submit-pr
  plan:
  - get: paketo-image
    tags: [buildpacks]
    passed: [test-buildpack-builder]
    trigger: true
  - task: pr
    tags: [buildpacks]
    on_failure:
      put: slack
      params:
        text: |
          :exclamation: $BUILD_PIPELINE_NAME pipeline failed at step $BUILD_JOB_NAME! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View>
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/bwb, tag: ((bwb-image-version)) } }
      inputs:
      - name: paketo-image
      params:
        CODE_ENGINE_REGISTRY: "icr.io/obs/codeengine/buildpacks"
        SOURCE_TO_IMAGE_REPOSITORY: "coligo/source-to-image"
      run:
        path: /bin/bash
        args:
        - -c
        - (( file "scripts/submit-pr.sh" ))
      