[[Buildpacks]]
  ID = "paketo-buildpacks/httpd"
  URI = "/tmp/httpd-cnb_a034e0c86277d15d8c4cb550"

[[Groups]]

  [[Groups.Buildpacks]]
    id = "paketo-buildpacks/httpd"
    name = ""
    version = "0.0.1"
